[package]
name = "moonrabbit-availability-distribution"
version = "0.1.0"
authors = ["Moon Rabbit <admin@moonrabbit.com>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
moonrabbit-scale-codec = { version = "2.0.0", features = ["std"]  }
moonrabbit-primitives = { path = "../../../primitives" }
moonrabbit-erasure-coding = { path = "../../../erasure-coding" }
moonrabbit-subsystem = { package = "moonrabbit-node-subsystem", path = "../../subsystem" }
moonrabbit-node-network-protocol = { path = "../../network/protocol" }
moonrabbit-node-subsystem-util = { path = "../../subsystem-util" }
moonrabbit-node-primitives = { path = "../../primitives" }
moonrabbit-node-core-runtime-api = { path = "../../core/runtime-api" }
sp-application-crypto = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
sp-core = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master", features = ["std"]  }
sp-keystore = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
thiserror = "1.0.23"
rand = "0.8.3"
lru = "0.6.5"

[dev-dependencies]
moonrabbit-subsystem-testhelpers = { package = "moonrabbit-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
sp-core = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master", features = ["std"] }
sp-keyring = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
sp-tracing = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
sc-keystore = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
sc-network = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
futures-timer = "3.0.2"
assert_matches = "1.4.0"
maplit = "1.0"
smallvec = "1.6.1"
