[package]
name = "moonrabbit-node-core-bitfield-signing"
version = "0.1.0"
authors = ["Moon Rabbit <admin@moonrabbit.com>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
moonrabbit-primitives = { path = "../../../primitives" }
moonrabbit-node-subsystem = { path = "../../subsystem" }
moonrabbit-node-subsystem-util = { path = "../../subsystem-util" }
sp-keystore = { git = "https://github.com/moonRabbitAZ/substrate", branch = "master" }
wasm-timer = "0.2.5"
thiserror = "1.0.23"

[dev-dependencies]
moonrabbit-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
